apiVersion: v1
kind: ServiceAccount
metadata:
  name: exchangerate-exporter
  labels:
    app.kubernetes.io/name: exchangerate-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: exchangerate-exporter
  labels:
    app.kubernetes.io/name: exchangerate-exporter
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9110
    targetPort: 9110
  selector:
    app.kubernetes.io/name: exchangerate-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchangerate-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: exchangerate-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exchangerate-exporter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - exchangerate-exporter
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: exchangerate-exporter
      containers:
      - name: exchangerate-exporter
        image: abeyuki/exchangerate-exporter:1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 800Mi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.25"
        env: 
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: avp-secret
              key: api_key
